# Generated by Django 6.0.4 on 2026-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Manager', 'manager'), ('User', 'user')], default='user', max_length=30),
        ),
    ]
