# Generated by Django 6.0.4 on 2026-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
