# Generated by Django 5.2.6 on 2026-04-22 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('Progress', 'Progress'), ('Done', 'Done')], default='Todo', max_length=100)),
                ('assigned_to', models.ForeignKey(choices=[('Todo', 'Todo'), ('Progress', 'Progress'), ('Done', 'Done')], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='projects.projects')),
            ],
        ),
    ]
